import Head from "next/head";
import { useEffect } from "react";
import { useSelector } from "react-redux"
import { useRouter } from "next/router"
// --- components
import Main from "../../components/Editor/Main";

export default function Editor() {
  const router = useRouter()
  const user = useSelector(state => state.auth.user)



  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container lg:w-2/3 px-4 md:px-16 my-8 mx-auto">
        <Main />
      </main>

      <script
        async
        charSet="utf-8"
        src="https://cdn.iframe.ly/embed.js?api_key=2abfe30316a925c0d0ef48"
      ></script>
    </div>
  );
}

// export async function getStaticProps(context) {
//   try {

//     let blogs = await axios.get(`/api/blogs`).then((res) => {
//       if (res.statusText === "OK") {
//         let blogs = [];
//         res.data.payload.blogs.map(blog => {
//           if(blog.draft) {
//             blogs.push(blog)
//           }
//         })
    
//         return blogs
//       }
//     });

//     return {
//       props: {
//         blogs,
//       }, // will be passed to the page component as props
//       revalidate: 60,
//     };
//   } catch (err) {
//     // console.log(err);
//     return { notFound: true };
//   }
// }
