import Head from "next/head";

// --- components
import Main from "../../components/Editor/Main";

export default function Editor() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container lg:w-2/3 px-4 md:px-16 my-8 mx-auto">
        <Main />
      </main>

      <script
        async
        charSet="utf-8"
        src="https://cdn.iframe.ly/embed.js?api_key=2abfe30316a925c0d0ef48"
      ></script>
    </div>
  );
}
