import Head from "next/head";
import axios from "../utils/axios";
import { useSelector } from "react-redux";


// --- components
import Main from "../components/Home/Main";


export default function Home({ blogs, user }) {
  const auth = useSelector((state) => state.auth);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!auth.isSignIn && !auth.isSignUp && (
        <main className="modal-animation lg:container grid grid-cols-6 px-4 md:px-8 lg:px-16 my-8 mx-auto">
          <Main blogs={blogs} />
        </main>
      )}
    </>
  );
}

export async function getStaticProps(context) {
  try {
    let blogs = await axios.get(`/api/blogs`).then((res) => {
      console.log(res);
      if (res.statusText === "OK") {
        let blog = res.data.payload.blogs;
        return blog;
      }
    });

    return {
      props: {
        blogs,
      }, // will be passed to the page component as props
      revalidate: 60,
    };
  } catch (err) {
    console.log(err);
    return { notFound: true };
  }
}


