import React from "react";
import Head from "next/head";
import axios from "../../../utils/axios";

// --- components
import Main from "../../../components/Post/Main";

function Post({ blog }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main blog={blog} />
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  try {
    let id = context.params.id;
    let blog = await axios.get(`/api/blogs/${id}`).then((res) => {
      console.log(res);
      if (res.statusText === "OK") {
        let blog = res.data.payload.blog;
        return blog;
      }
    });

    return {
      props: {
        blog,
      }, // will be passed to the page component as props
      revalidate: 60,
    };
  } catch (err) {
    console.log(err);
    return { notFound: true };
  }
}

export async function getStaticPaths() { 
  try {

    let blogs = await axios.get(`/api/blogs`).then((res) => {
      console.log(res);
      if (res.statusText === "OK") {
        let blogs = res.data.payload.blogs;
        return blogs;
      }
    });
    const paths = blogs.map((blog) => ({
      params: { id: blog._id, user: "user" },
    }))

    return {
      paths,
      fallback: false
    };
  } catch (err) {
    console.log(err);
    return { fallback: false };
  }
}


export default Post;
